# An example
---
fixtures:
  forge_modules:
     simplib:
        repo: "simp/simplib"
        ref: "3.15.3"
     stdlib:
        repo: "puppetlabs/stdlib"
        ref: "5.2.0"
symlinks:
  multi_node: "#{source_dir}"
